version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: docs/

sphinx:
  builder: dirhtml
  fail_on_warning: true
  configuration: docs/conf.py


formats:
  - pdf
  - epub
